version: "3"

services:
  vscode_extension_sample:
    container_name: vscode_extension_sample
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ../:/app/
    ports:
      - "8080:8080"
    command: sleep infinity
